[package]
name = "hkdf"
version = "0.8.1-alpha.0"
authors = ["vladikoff", "warner", "RustCrypto Developers"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/RustCrypto/KDFs/"
repository = "https://github.com/RustCrypto/KDFs/"
description = "HMAC-based Extract-and-Expand Key Derivation Function (HKDF)"
keywords = [ "HKDF", "Crypto" ]
readme = "README.md"

[features]
std = []

[lib]
name = "hkdf"
path = "src/hkdf.rs"

[dependencies]
digest = "= 0.9.0-pre"
hmac = "= 0.8.0-pre"

[dev-dependencies]
crypto-tests = "0.5.*"
hex = "0.4.0-pre"
sha-1 = "0.9.0-pre"
sha2 = "0.9.0-pre"
bencher = "0.1"

[[bench]]
name = "hkdf"
harness = false
